### ISSUE TITLE
eb --new-pr crashes

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild#358]
I am trying to use `eb --new-pr` to submit a patch.  `eb --check-github` passes all tests.

```
eb --new-pr Tensorflow-1.2.1-foss-2016b-Python-3.6.1.eb protobuf-python-3.3.0-foss-2016b-Python-3.5.2.eb protobuf-3.3.0-foss-2016b.eb 
== temporary log file in case of crash /tmp/eb-_MLDRi/easybuild-tAuuys.log

[ ... elided ... ]

 * overview of changes:
 easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.3.0-foss-2016b-Python-3.5.2.eb | 29 +++++++++++++++++++++++++++++
 easybuild/easyconfigs/p/protobuf/protobuf-3.3.0-foss-2016b.eb                            | 23 +++++++++++++++++++++++
 easybuild/easyconfigs/t/Tensorflow/Tensorflow-1.2.1-foss-2016b-Python-3.5.2.eb           | 51 +++++++++++++++++++++++++++++++++++++++++++++++++++
 3 files changed, 103 insertions(+)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/main.py", line 478, in <module>
    main()
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/main.py", line 401, in main
    commit_msg=options.pr_commit_msg)
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/tools/github.py", line 926, in new_pr
    status, data = pulls_url.post(body=body)
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/home/modules/software/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 635, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib64/python2.7/urllib2.py", line 596, in redirect_request
    raise HTTPError(req.get_full_url(), code, msg, headers, fp)
urllib2.HTTPError: HTTP Error 307: Temporary Redirect
```

This could perhaps be a temporary github error, but more likely they have moved something and `eb` chokes on the redirect.  The problem has been present all day.

**Comment by boegel** [comment]
@schiotz See https://github.com/easybuilders/easybuild-framework/issues/2257 (which mentions a workaround).
This was fixed with https://github.com/easybuilders/easybuild-framework/pull/2258, which is included in the upcoming EasyBuild v3.3.1 release.
