### ISSUE TITLE
Trying to build inside a container fails

### ISSUE THREAD

**Issue by adrianreber** [easybuilders/easybuild#601]
Building a simple application using easybuild in a container works, but building a larger dependency chain fails with strange errors:
```
[mpi@rhel05 containers]$ podman run quay.io/ohpc/ohpc-gnu9-easybuild:1.9.9 'eb --robot lz4-1.9.2-GCCcore-8.3.0.eb' 
== temporary log file in case of crash /tmp/eb-2d8lhzz7/easybuild-hvv_jsdf.log
== resolving dependencies ...
== processing EasyBuild easyconfig /opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/easybuild/easyconfigs/m/M4/M4-1.4.18.eb
== building and installing M4/1.4.18...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
ERROR: Traceback (most recent call last):
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/base/fancylogger.py", line 585, in logToFile
    os.makedirs(directory)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
FileExistsError: [Errno 17] File exists: '/tmp/eb-2d8lhzz7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/main.py", line 113, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3206, in build_and_install_one
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 296, in close_log
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/base/fancylogger.py", line 588, in logToFile
    raise_with_traceback(exc, "Cannot create logdirectory %s: %s \n detail: %s" % (directory, ex, detail), tb)
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/tools/py2vs3/py3.py", line 75, in raise_with_traceback
  File "/opt/ohpc/pub/libs/easybuild/4.1.1/software/EasyBuild/4.1.1/lib/python3.6/site-packages/easybuild/base/fancylogger.py", line 585, in logToFile
    os.makedirs(directory)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
FileExistsError: Cannot create logdirectory /tmp/eb-2d8lhzz7: [Errno 17] File exists: '/tmp/eb-2d8lhzz7' 
 detail: [Errno 17] File exists: '/tmp/eb-2d8lhzz7'
```

Full debug log available at: [eb1.log](https://github.com/easybuilders/easybuild/files/4225349/eb1.log)

The host is running RHEL8 and the container is based on the latest CentOS 8 container image.

**Comment by adrianreber** [comment]
There is a segfault in fuse-overlayfs. Closing this as it seems to be an error in the rootless overlayfs driver.

**Comment by adrianreber** [comment]
Fixed in https://github.com/containers/fuse-overlayfs/issues/169

**Comment by boegel** [comment]
@adrianreber The bug explains why the `configure` failed, but the traceback reported by EasyBuild is still weird, it shouldn't be crashing like that but telling us the `configure` failed...

So, I'll re-open this and move it to the `easybuild-framework` repository (since that's where we should avoid raising the traceback).
