### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by serverhorror** [easybuilders/easybuild#75]
Hello,

I am trying to bootstrap easybuild and it fails. I can't for the life of it figure out why. I suspect that there is a problem downloading the `easybuild-framework-1.16.1.tar.gz` because of our corporate proxy.

I have attached what I think (and hope) is useful. Interestingly enough the installation with pip works. (see end of the issue).
**bootstrap_eb.py**

```
$ python -V
Python 2.6.6
```

```
$ type module
module is a function
module ()
{
    eval `/usr/bin/modulecmd bash $*`
}
```

```
$ type -f module
-bash: type: module: not found
```

```
$ python bootstrap_eb.py $HOME/.local/easybuild
[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[INFO]]

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmp1ObkZj
Now working in /tmp/tmp1ObkZj/distribute-0.6.34
Installing Distribute
[[INFO]]

+++ STAGE 1: installing EasyBuild in temporary dir with easy_install...


Installing with setuptools.setup...
Installing version 1.16.1
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
zip_safe flag not set; analyzing archive contents...
Installing with setuptools.setup...
Installing version 1.16.1 (API version 1)
Installing with setuptools.setup...
Installing version 1.16.1 (required versions: API >= 1)
Installing with setuptools.setup...
Installing version 1.16.1.0 (required versions: API >= 1, easyblocks >= 1.16)
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
[[INFO]]

+++ STAGE 2: installing EasyBuild in $HOME/.local/easybuild with EasyBuild from stage 1...


== temporary log file in case of crash /tmp/easybuild-GucYtD/easybuild-pwkEFT.log
== processing EasyBuild easyconfig /tmp/tmpj2OkV2/EasyBuild-1.16.1.eb
== building and installing EasyBuild/1.16.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpj2OkV2/EasyBuild/1.16.1/dummy-dummy): build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/tools/run.py:382 in parse_cmd_output): cmd "tar xzf /tmp/tmpj2OkV2/sources/e/EasyBuild/easybuild-framework-1.16.1.tar.gz" exited with exitcode 2 and output:

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable:
== Results of the build can be found in the log file /tmp/easybuild-GucYtD/easybuild-EasyBuild-1.16.1-20150126.162203.bLPPh.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 584, in <module>
    main()
  File "bootstrap_eb.py", line 411, in main
    stage2(tmpdir, versions, install_path)
  File "bootstrap_eb.py", line 360, in stage2
    easybuild_main()
  File "/tmp/tmpj2OkV2/eb_stage1/lib/python2.6/site-packages/easybuild_framework-1.16.1-py2.6.egg/easybuild/main.py", line 305, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpj2OkV2/eb_stage1/lib/python2.6/site-packages/easybuild_framework-1.16.1-py2.6.egg/easybuild/main.py", line 138, in build_and_install_software
    _log.error(test_msg)
  File "/tmp/tmpj2OkV2/eb_stage1/lib/python2.6/site-packages/easybuild_framework-1.16.1-py2.6.egg/easybuild/tools/build_log.py", line 109, in error
    raise EasyBuildError(newMsg)
easybuild.tools.build_log.EasyBuildError: 'EasyBuild crashed with an error (at easybuild/main.py:138 in build_and_install_software): Build of /tmp/tmpj2OkV2/EasyBuild-1.16.1.eb failed (err: \'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/tools/run.py:382 in parse_cmd_output): cmd "tar xzf /tmp/tmpj2OkV2/sources/e/EasyBuild/easybuild-framework-1.16.1.tar.gz" exited with exitcode 2 and output:\\n\\ngzip: stdin: unexpected end of file\\ntar: Child returned status 1\\ntar: Error is not recoverable: \')'
```

```
$ file /tmp/tmpj2OkV2/sources/e/EasyBuild/easybuild-framework-1.16.1.tar.gz
/tmp/tmpj2OkV2/sources/e/EasyBuild/easybuild-framework-1.16.1.tar.gz: empty
```

```
$ curl --location -I http://pypi.python.org/packages/source/e/easybuild-framework/easybuild-framework-1.16.1.tar.gz
HTTP/1.1 301 Moved Permanently
Server: Varnish
Retry-After: 0
Location: https://pypi.python.org/packages/source/e/easybuild-framework/easybuild-framework-1.16.1.tar.gz
Accept-Ranges: bytes
Date: Mon, 26 Jan 2015 15:22:41 GMT
X-Served-By: cache-ams4145-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1422285761.864839,VS0,VE0
Content-Length: 0
Via: 1.1 varnish, 1.1 proxy.example.invalid:3128 (Cisco-IronPort-WSA/7.5.2-303), 1.1 proxy.example.invalid:80 (Cisco-IronPort-WSA/7.5.2-303)
Connection: keep-alive
Proxy-Connection: keep-alive

HTTP/1.1 200 Connection established
Date: Mon, 26 Jan 2015 15:22:42 GMT
Via: 1.1 proxy.example.invalid:80 (Cisco-IronPort-WSA/7.5.2-303)
Connection: close
Proxy-Connection: close

HTTP/1.1 200 OK
Date: Mon, 26 Jan 2015 15:22:42 GMT
Server: nginx/1.6.2
Content-Type: application/octet-stream
X-PyPI-Last-Serial: 1354299
ETag: 65fc39572af03c3fb75d7dd45cb6c272
Cache-Control: max-age=31557600, public
Strict-Transport-Security: max-age=31536000; includeSubDomains
Public-Key-Pins: max-age=600; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU="; pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI="; pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";
Via: 1.1 varnish
Content-Length: 1350742
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 65862
X-Served-By: cache-iad2124-IAD, cache-ams4142-AMS
X-Cache: HIT, MISS
X-Cache-Hits: 1, 0
X-Timer: S1422285762.264909,VS0,VE496
```

**Hacky Install with `pip install -U --proxy="..." --install-option "--prefix=$HOME/EasyBuild" easybuild`**

After setting up `PATH` and `PYTHONPATH` the installation of `eb Python-2.7.8-foss-2014b.eb --robot` also fails:

```
$ echo $PYTHONPATH
/net/home/marcherm/EasyBuild/lib/python2.7/site-packages/
$ eb Python-2.7.8-foss-2014b.eb --robot
== temporary log file in case of crash /tmp/easybuild-o_MobI/easybuild-daWA9C.log
== resolving dependencies ...
== processing EasyBuild easyconfig /net/home/marcherm/EasyBuild/easybuild/easyconfigs/g/GCC/GCC-4.8.3.eb
== building and installing GCC/4.8.3...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== FAILED: Installation ended unsuccessfully (build directory: /net/home/marcherm/.local/easybuild/build/GCC/4.8.3/dummy-dummy): build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/tools/run.py:382 in parse_cmd_output): cmd "tar xzf /net/home/marcherm/.local/easybuild/sources/g/GCC/gcc-4.8.3.tar.gz" exited with exitcode 2 and output:

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive

== Results of the build can be found in the log file /tmp/easybuild-o_MobI/easybuild-GCC-4.8.3-20150126.164243.JXZPt.log
ERROR: EasyBuild crashed with an error (at easybuild/main.py:138 in build_and_install_software): Build of /net/home/marcherm/EasyBuild/easybuild/easyconfigs/g/GCC/GCC-4.8.3.eb failed (err: 'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/tools/run.py:382 in parse_cmd_output): cmd "tar xzf /net/home/marcherm/.local/easybuild/sources/g/GCC/gcc-4.8.3.tar.gz" exited with exitcode 2 and output:\n\ngzip: stdin: unexpected end of file\ntar: Unexpected EOF in archive\ntar: Unexpected EOF in archive\n')
```

**Comment by ZAM-** [comment]
Have you tried a different version of GCC? It seems like there might be a problem with the archive the eb file is pointing at. 

Also, if you can download the source, you could point the source_path to it and test things that way too.

**Comment by boegel** [comment]
@serverhorror: what kind of MD5 sum are you getting for both the `easybuild-framework-1.16.1.tar.gz` and `gcc-4.8.3.tar.gz` tarballs?

Currently, there's no support for downloading via a proxy in EasyBuild (I'm not sure how difficult that would be), but you can feed it the sources; if `eb` finds the sources it requires in the source path (by default `$HOME/.local/easybuild/sources`, but can be configured to something else, see http://easybuild.readthedocs.org/en/latest/Configuration.html#sourcepath), it won't try to download them.

For now, the bootstrap script doesn't support supplying it tarballs, but that's something we'll need to look into soon anyway.

**Comment by serverhorror** [comment]
Hey,

No I haven't tried with a different version of GCC. This is a stock Centos6.5 and eb hasn't been installed yet. Basically it's step 0 from the installation manual: http://easybuild.readthedocs.org/en/latest/Installation.html#bootstrapping-procedure

Yes the downloaded eb archive is broken (zero file length).

I guess the problem is this:

> Currently, there's no support for downloading via a proxy in EasyBuild

Did you do something to prevent that? Haven't looked into the code as of yet, but afaik Python and Requests do "the right thing"(TM) with the `..._proxy` variables, if they are set.

**Comment by Flamefire** [comment]
This is probably fixed now. Even if downloading via Python fails there is EASYBUILD_BOOTSTRAP_SOURCEPATH env var which can be set to a folder containing tarballs downloaded via different means. There is nothing added (anymore?) which changes Pythons default download, so even that might work. With https://github.com/easybuilders/easybuild-framework/pull/3186 you can also try to use Python3

**Comment by serverhorror** [comment]
From my point of view this is fixed. I'm sorry I forgot about this it has been working for a while.
