### ISSUE TITLE
OpenSSL easyconfig fails to build with various python3 versions

### ISSUE THREAD

**Issue by doswellf** [easybuilders/easybuild#864]
Have tried to build foss22.10.eb in various virtualenv instances using  pyenv.
Tried 3.10.9, 3.8.15, 3.7.15, 3.9.7 in separate virtualenvs. In all cases I get a LooseVersion-related error that stops OpenSSL from building and installing. Ubuntu 22 on and AMD 12-core with a big AMD gfx1030-series gpu. Lots of memory and disk space too. Here is the message:

`eb /home/py3user/.pyenv/versions/ebtest471/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb
== Temporary log file in case of crash /tmp/eb-0rwc_18y/easybuild-z3dgf5tz.log
== found valid index for /home/py3user/.pyenv/versions/ebtest471/easybuild/easyconfigs, so using it...
== processing EasyBuild easyconfig /home/py3user/.pyenv/versions/ebtest471/easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.eb
ERROR: Traceback (most recent call last):
  File "/home/py3user/.pyenv/versions/ebtest471/lib/python3.10/site-packages/easybuild/main.py", line 133, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/py3user/.pyenv/versions/ebtest471/lib/python3.10/site-packages/easybuild/framework/easyblock.py", line 4174, in build_and_install_one
    app = app_class(ecdict['ec'])
  File "/home/py3user/.pyenv/versions/ebtest471/lib/python3.10/site-packages/easybuild/easyblocks/o/openssl_wrapper.py", line 178, in __init__
    if LooseVersion(openssl_version) >= LooseVersion(min_openssl_version):
  File "/home/py3user/.pyenv/versions/ebtest471/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 90, in __ge__
    c = self._cmp(other)
  File "/home/py3user/.pyenv/versions/ebtest471/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 350, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
`
I even tried to hack the openssl.py in the easyconfigs but that just created a chain-reaction of more errors.  

Not sure how to debug this one, as I use python but haven't gone that deep into package development. And easybuild was supposed to prevent that anyways.

**Comment by boegel** [comment]
This looks like a bug in the `setuptools` installation being used here...
Which Python package versions do you have installed in that environment?
